apiVersion: apps/v1
kind: Deployment
metadata:
  name: kzegani-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kzegani-playground
  template:
    metadata:
      labels:
        app: kzegani-playground
    spec:
      containers:
        - name: kzegani-playground
          image: kzegani/inception-of-things-p3-app:v1
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: kzegani-playground
  namespace: dev
spec:
  selector:
    app: kzegani-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
